remoteintech/remote-jobs

- README.md
We're fully remote/distributed.
> Added Rocana

- README.md
Estately has remote devs across the US and Europe.
> Added Estately to list of remote friendly companies

- README.md
> Add &yet to the list

- README.md
All of our team members (5 people) are working remotely doing JS/front-end development.
> Add Functionite – a completely remote JS development house.

- README.md
:white_check_mark: Verified, and fully remote. http://testdouble.com/
> Add Test Double

- README.md
We've got distributed workers in every department of our company. At the moment, 75% of our developers are remote, working from across the US and Europe.
> Add Haiku Learning

- README.md
All of their employees are remote
> Adding Filament Group

- README.md
> Add DNSimple

- README.md
> add influxdb

- README.md
SmugMug is roughly half remote.
> Add SmugMug

- README.md
Sorry, I had to recreate the PR because of git issues.
Something else to note: A few companies were not alphabetized correctly so I fixed that as well.
In case anyone is interested in doing this again, I wrote this ruby script to pull companies from WeWorkRemotely and add them to the document. This works on Ruby 2.2.2 without any dependencies.
```ruby
require 'rss'
require 'open-uri'
require 'cgi'
@failure = 0
def url(id)
"https://weworkremotely.com/categories/#{id}-this-attribute-doesnt-matter/jobs.rss"
end
def company_name(item)
/(.*):/.match(item.title)[1]
end
def company_url(item)
begin
uri = URI(/<a href="(.*)">/.match(item.description)[1])
uri.scheme + '://' + uri.host
rescue URI::InvalidURIError
puts "ITEM FAILED:\n"
puts company_name(item) rescue "Name and URL parse failed" …
```
> Add companies from WeWorkRemotely. Fixes #34.

- README.md
> Offices column

- README.md
Hey,
I work for CFPB, an agency of the federal government that makes the consumer financial marketplace work fairly for everyone. Our tech department is remote with developers in the SF Bay and LA, across Chicagoland, Connecticut, Vermont and more.
We also have another website for just articles about our tech team at http://cfpb.github.io/.
> Added CFPB

- README.md
Adding the company I co-founded, @rainforestapp. We love remote, but also have an office in SF if you're based here. We have 8 remote engineers and 2 in SF :)
> Add Rainforest QA

- README.md
Fastly has lots of remote people so I'd like to add it to the list.
(Thanks for organizing this repo. :smile:)
> Add Fastly to README

- README.md
- company-profiles/bluebottlecoffee.md
Blue Bottle has several remote software engineers including @pwnela (Atlanta) @caseygipson (Denver) @dlachasse (Portland).
> Add Blue Bottle Coffee

- README.md
- company-profiles/puppetlabs.md
- incremented company count.
- added profile and link
> Added Puppetlabs

- README.md
See a preview here: https://github.com/hkdobrev/remote-jobs/tree/link-company-name-to-profile
> Remove profile column, link company name to profile instead

- README.md
- company-profiles/10up.md
> Add profile and fill out info for 10up

- CONTRIBUTING.md
- README.md
Closes https://github.com/jessicard/remote-jobs/issues/72
Uses [GitHub convention](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
> Move contributing guidelines to CONTRIBUTING.md

- README.md
Currently in US, Turkey, Denmark, Romania & Poland
> add Koding

- README.md
- company-profiles/fullfabric.md
Incremented the list and added the company profile page as well.
Thanks a lot and have fun!
> Add FullFabric company profile

- README.md
- company-profiles/spoqa.md
Hi,
I’m JC, Co-founder of [Spoqa, Inc](https://www.spoqa.com/).
We are providing remote working system so that I made this pull request.
Please review this pull request and if you have a question, feel free to ask me.
> Add Spoqa, Inc.

- README.md
- company-profiles/dramafever.md
DramaFever!
We are headquartered in New York NY and Philadelphia PA but very remote friendly!
> Add DramaFever

- README.md
- company-profiles/andyet.md
> Add &yet profile

- README.md
- company-profiles/rtCamp.md
Hi @jessicard 
I hope I have adhered to all your guidelines, kindly add rtCamp's profile to repository.
Thanks,
--Harshad
> Add rtCamp's company profile

- README.md
They don’t have a careers section however they are looking
https://twitter.com/letsencrypt/status/653981879754821632
> Added Let's Encrypt

- README.md
- company-profiles/bigwheelbrigade.md
This PR adds Big Wheel Brigade to the list of remote jobs and adds a BWB profile page.
> Adds Big Wheel Brigade

- CONTRIBUTING.md
... so it doesn't show up as a bullet point.
> escape the *asterisk line

- README.md
This PR updates Harvest's region to Everywhere.
> Update Harvest's region

- README.md
- company-profiles/platformsh.md
As a truly, fully distributed team... I kindly ask you for inclusion.
> Adding platform.sh profile

- README.md
> Add GitPrime to the list

- README.md
- company-profiles/omniti.md
> Add OmniTI

- README.md
- company-profiles/elastic.md
Add Elastic.
We have over 280 employees around 40(?) countries. Most of us are work
remotely. :)
> Add Elastic

- README.md
- company-profiles/zeitio.md
> Adding Zeit.io to the list of remote jobs.

- README.md
I can add the company profile next week
> feat(AngularClass): region

- README.md
- company-profiles/dnsimple.md
I've updated our entry with a profile document.
> Add DNSimple profile.

- company-profiles/18F.md
> Replace accidental indent with a plus

- README.md
- company-profiles/mapbox.md
Info copied directly from the Mapbox website. Nothing concrete to be found on remote work. Maybe the @mapbox team could add it themselves.
> Add mapbox

- README.md
- company-profiles/bandcamp.md
- company-profiles/etsy.md
> More profiles, Etsy, Bandcamp

- README.md
- company-profiles/gitprime.md
> Add GitPrime company profile

- README.md
> Add new company

- README.md
> Add Featurist

- README.md
- company-profiles/gormanhealthgroup.md
Also looks like my editor trimmed a trailing space in the README ;)
> Add Gorman Health Group

- README.md
- company-profiles/corgibytes.md
- company-profiles/edgar.md
- company-profiles/knack.md
Updated previous pull request by adding link to company profile directly from README.md
> Added Edgar, Knack and Corgibytes

- README.md
Hi there,
I added my awesome employer GoHiring. :smile_cat:
> Add GoHiring to the remote list

- README.md
- company-profiles/digitalocean.md
- company-profiles/harvest.md
- company-profiles/intercom.md
And a few other profiles to flesh out. I'll commit more tomorrow
> more companies - DigitalOcean, Harvest, Intercom

- README.md
> Added two remote companies

- README.md
- company-profiles/tech-angels.md
> Add Tech-Angels profile

- README.md
- company-profiles/zeitio.md
- Fixed the URL in the description of Zeit.io. (I think it was working before, not sure about it).
- Fixed the postal address in zeitio.md inside the company-profiles/ directory.
> Fixed the URL description and the postal address in Zeit.io

- README.md
- company-profiles/17hats.md
- company-profiles/apartmenttherapy.md
- company-profiles/automattic.md
- company-profiles/basecamp.md
- company-profiles/hugo.md
- company-profiles/iwantmyname.md
- company-profiles/stackexchange.md
> [ :shipit: ] More companies

- company-profiles/casumo.md
- company-profiles/fullfabric.md
- company-profiles/gigsalad.md
- company-profiles/github.md
Changes taken from styling of name from project page
http://sass-lang.com/
> Correct capitalization of Sass preprocessor

- README.md
Tag1 and PreviousNext both have remote employees.
> Add other remote friendly companies

- README.md
Disclaimer: I'm a remote engineer for Heap.
> Update Heap description

- README.md
- company-profiles/treehouse.md
> Adds Treehouse company profile

- README.md
- company-profiles/citrusbyte.md
Hi there,
We would like [Citrusbyte](https://citrusbyte.com/) to be added to this list. 
Let me know if there is anything missing!
> Add Citrusbyte company profile

- README.md
- company-profiles/discourse.md
- company-profiles/stripe.md
- company-profiles/toggl.md
There are some companies that might be remote and have offered one job and have been included in this list almost by error
> More companies

- README.md
- company-profiles/bandzoogle.md
- company-profiles/canonical.md
- company-profiles/cartodb.md
- company-profiles/hudl.md
- company-profiles/toptal.md
Added some new companies (Hudl, Bandzoogle) and completed profiles for existing companies.
> Bunch more companies

- README.md
Hireology is a company based out of Chicago, operating a ruby on rails application that delivers job applicant metrics. Their developer team is 100% remote or close to it.
> Added Hireology

- README.md
- company-profiles/baremetrics.md
- company-profiles/chargify.md
- company-profiles/clevertech.md
- company-profiles/ghost.md
- company-profiles/zapier.md
I'd say leave it open but I edited readme.md by making "Everywhere" into "Worldwide" :earth_africa: :earth_americas: :earth_asia:  I might cause the odd merge conflict :hammer:  whoops :sunglasses:  Because I like breaking things but mainly because that's what is mentioned in CONTRIBUTING.md :+1:
> Aaaaaaaand some more

- README.md
Azoolla is a startup of currently 3 people in the process of remotely building a beta for a web-based platform.
> Add Azoolla.

- README.md
- company-profiles/appstractor.md
- company-profiles/atomic-squirrel.md
I've going through the list and deleting companies who aren't looking for employees, only contributors (like Android Authority for blog articles) or similar.
Just ship this one when you're ready so I can get an employee of one of the companies to contribute.
> Starting another bunch

- README.md
- company-profiles/17hats.md
- company-profiles/acquia.md
- company-profiles/articulate.md
- company-profiles/automattic.md
- company-profiles/bandcamp.md
- company-profiles/bandzoogle.md
- company-profiles/basecamp.md
- company-profiles/chef.md
- company-profiles/digitalocean.md
- company-profiles/discourse.md
- company-profiles/etsy.md
- company-profiles/example.md
- company-profiles/formstack.md
- company-profiles/github.md
- company-profiles/harvest.md
- company-profiles/hugo.md
- company-profiles/iwantmyname.md
- company-profiles/stackexchange.md
- company-profiles/toggl.md
- company-profiles/wikimedia-foundation.md
- company-profiles/zapier.md
A few more companies and edits
> Another batch of profiles and updated copy

- CONTRIBUTING.md
- README.md
- company-profiles/auth0.md
- company-profiles/basho.md
- company-profiles/edgar.md
- company-profiles/mapbox.md
After some [googling](http://english.stackexchange.com/questions/159018/the-usa-vs-the-us), I can update the grammar and style of the readme a bit better. All instances of USA are now US. 
I've noticed some profiles must be in an old form or something as they're missing sections so I'm going to update the contributing with a few clarifications so people can expand in future rather than just delete parts.
> "The usual"

- company-profiles/heap
- company-profiles/heap.md
Thanks for setting up this repo, @jessicard! Happy we can be a part of it.
> Add company profile for Heap.

- README.md
- company-profiles/simplabs.md
Hello @jessicard, would you add us to the list please?
cheers
Oliver
> Add simplabs

- README.md
- company-profiles/netsparker.md
> Add Netsparker.

- README.md
- company-profiles/artefactual.md
Disclaimer: I work for Artefactual.
> Add Artefactual

- README.md
- company-profiles/bitovi.md
- company-profiles/envato.md
- company-profiles/kissmetrics.md
- company-profiles/wildbit.md
Add several companies to the list.
> Add several companies

- README.md
I noticed there were some duplicates and mis-alphabetized entries, so I cleaned up the list a little and removed those duplicates.
> Alphabetize list and removed duplicates

- README.md
The company behind Varnish Cache.
> Adding Varnish Software

- README.md
* Add meetedgar to company list
> Add meetedgar

- README.md
Created with https://github.com/dkhamsing/frankenstein
Was | Now 
--- | --- 
http://bulutyazilim.com/ | https://bulutyazilim.com/ 
http://gitprime.com/ | https://gitprime.com/ 
http://peachworks.com/ | https://peachworks.com/ 
http://realhq.com/ | https://realhq.com/ 
http://tag1consulting.com/ | https://tag1consulting.com/ 
http://www.acquia.com/ | https://www.acquia.com/ 
http://www.fournova.com/ | https://www.fournova.com/ 
http://www.helpscout.net/ | https://www.helpscout.net/ 
http://www.toptal.com/ | https://www.toptal.com/ 
Was | Now 
--- | --- 
http://cartstack.com | http://www.cartstack.com/ 
http://parkerwallace.com | http://www.parkerwallace.com/ 
http://www.appstractor.com | https://www.appstractor.com/ 
http://www.axelerant.com/ | https://axelerant.com/ …
> Update README URLs based on HTTP redirects and Renaming

- PULL_REQUEST_TEMPLATE.MD
> amend PR template

- README.md
- company-profiles/fogcreek.md
> Added Fog Creek Software

- README.md
- company-profiles/happybearsoftware.md
> Add happybearsoftware

- company-profiles/automattic.md
> Automattic - just some minor copy edits / updates :)

- README.md
- [ X ] This PR contains housekeeping (URL edits, copy changes etc)
> Update wikimedia foundation link

- README.md
- company-profiles/novoda.md
> Add Novoda

- README.md
- company-profiles/inquicker.md
> Add InQuicker

- README.md
- company-profiles/udacity.md
> Add Udacity

- README.md
- company-profiles/simple.md
> Update location and company profile for Simple

- README.md
- company-profiles/rackspace.md
This PR adds a company profile and index listing for Rackspace
> Adds Rackspace profile

- README.md
- company-profiles/allydvm.md
> Add allyDVM

- company-profiles/novoda.md
> Fixes grammatical mistakes and changes Swift to iOS.

- README.md
> Adding Big Cartel

- company-profiles/bigcartel
> create Big Cartel profile

- README.md
- company-profiles/server-density.md
> Added Server Density

- README.md
> Add Focusnetworks

- README.md
- company-profiles/dgraph.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jessicard/remote-jobs/226)
> adding profile for DGraph

- README.md
- company-profiles/new_context.md
> add New Context company

- README.md
- company-profiles/hireology.md
> Add company profile for Hireology

- README.md
- company-profiles/mixmax.md
> Add Mixmax.

- README.md
- company-profiles/spreedly.md
> Add Spreedly

- README.md
- company-profiles/mediacurrent.md
> Adding Mediacurrent to the remote-jobs list

- README.md
- company-profiles/simpletexting.md
- [xI am an employee of the company mentioned and confirm all details are correct
> Add simpletexting

- README.md
This company is already on line 91.
> Remove duplicate entry (Edgar)

- README.md
- company-profiles/crowdtangle.md
> Add CrowdTangle

- README.md
- company-profiles/ushahidi.md
> Add Ushahidi

- README.md
- company-profiles/hackreactorremote.md
This PR only modifies existing information.
---
> Update Hack Reactor Remote information

- README.md
- company-profiles/anexus.md
> Add Anexus a LATAM company

- README.md
- company-profiles/dronedeploy.md
> add dronedeploy

- README.md
I work at Park Assist and I attest that it belongs in this list. Our HQ is in NYC and we have team members in in Florida, Seattle, and Buenos Aires.
Thank you!
> Add Park Assist

- README.md
- company-profiles/park-assist.md
> Add profile for Park Assist

- README.md
- company-profiles/redhat.md
> Add profile for Red Hat

- README.md
- company-profiles/sixtostart.md
> Adds Six to Start to the listings

- README.md
- company-profiles/mtc.md
> Added mtc.

- README.md
- company-profiles/prezly.md
- [*] You know your alphabet - company is listed in alphabetical order in the README
- [*] A company profile is included - Not essential but it really helps!
- [*] The company directly hires employees - This may sounds odd but while awesome, this list is not for coding bootcamps, "teaching" positions a network (Teacher positions employed directly, such as Treehouse, are allowed), or networking sites for listing a CV looking for gigs
- [*] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [*] A company-profile has been included for each addition to the …
> added Prezly

- README.md
- company-profiles/caremessage.md
> Adding CareMessage

- README.md
- company-profiles/codeait.md
> Added Codea IT

- company-profiles/zapier.md
- [ +] This PR contains housekeeping (URL edits, copy changes etc)
- [ +] You know your alphabet - company is listed in alphabetical order in the README
- [ +] A company profile is included - Not essential but it really helps!
- [ +] The company directly hires employees - This may sounds odd but while awesome, this list is not for coding bootcamps, "teaching" positions a network (Teacher positions employed directly, such as Treehouse, are allowed), or networking sites for listing a CV looking for gigs
- [ +] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as …
> updated zapier.md

- README.md
Based on their description in the blog post (http://blog.arkency.com/join-our-team).
> Add region for Arkency

- README.md
Based on the description in one of the job openings (https://audiense.com/about-us/careers/data-visualization-analyst).
> Add region for Audiense

- README.md
- company-profiles/agflow.md
> Add AgFlow

- company-profiles/automattic.md
> Update information about Automattic company

- README.md
- company-profiles/hyperion.md
> Added Hyperion Development South Africa

- README.md
- company-profiles/dalenys.md
> Add Dalenys (https://dalenys.com/)

- README.md
- company-profiles/codepen.md
Added [CodePen.io](https://codepen.io) - their team is 100% remote.  In CodePen Radio episode 77 they delve into how it benefits them: https://blog.codepen.io/2016/02/16/077-remote/
> Add CodePen

- README.md
- company-profiles/percona.md
> Added Percona

- README.md
- company-profiles/litmus.md
> add Litmus to list of companies, per contributor guidelines

- README.md
- company-profiles/evilmartians.md
> Add Evil Martians

- company-profiles/evilmartians.md
> Fix typo in evilmartians

- README.md
- company-profiles/conversio.md
> Conversio Company Added

- company-profiles/hireology.md
> fix broken link to careers page

- README.md
> Adding Yonder

- README.md
- company-profiles/alphasights.md
> Add AlphaSights

- README.md
- company-profiles/artandlogic.md
This PR adheres to the Pull Request Template, except for the fact that I am not employed at the company. 
I have an informal list of remote companies which includes some others not found in your list and am happy to submit more PRs if it is helpful.
Thanks!
> Adds Art&Logic

- README.md
- company-profiles/artandlogic.md
- company-profiles/noredink.md
> Add NoRedInk

- README.md
- company-profiles/agilebits.md
> Add AgileBits to README and created company profile

- README.md
- company-profiles/circonus.md
> Add Circonus

- README.md
- company-profiles/recharge.md
> Adding ReCharge to list of remote companies. 

- README.md
- company-profiles/honeycomb.md
> Add Honeycomb!

- README.md
- company-profiles/recharge.md
> Fixed link for ReCharge

- README.md
> Fix typos for AgileBits entry

- company-profiles/discourse.md
> Updated Discourse info

- README.md
- company-profiles/getaround.md
> Add Getaround to the list

- company-profiles/zapier.md
👋 Hello! My name is Julia Elman and I am the Design Team Manager at [Zapier](https://zapier.com/) and noticed this copy needed some updating. Also, thank you for maintaining this list! Super helpful in getting the word out to folks about remote companies 💯
> Update Zapier company profile.

- README.md
- company-profiles/hanzo.md
> Add Hanzo Archives to the list.

- README.md
- company-profiles/datasciencebrigade.md
- [x ] You know your alphabet - company is listed in alphabetical order in the README
> Adds Data Science Brigade information

- README.md
- company-profiles/adhoc.md
> Add Ad Hoc

- README.md
- company-profiles/findify.md
> Added Findify

- README.md
- company-profiles/pagerduty.md
> Add PagerDuty to list of companies

- README.md
- company-profiles/customerio.md
> Adding + fixing Customer.io

- README.md
Removes unresponsive sites for:
- Rails Dog
- Rival Fox
- Sqwiggle
- Tribe.net
Updated link for:
- TractionBoard (from .io to .com)
> Remove Inactive Links from Readme

- README.md
- company-profiles/manifold.md
> Add Manifold

- README.md
- company-profiles/bitnami.md
> Adding bitnami to the list

- README.md
- company-profiles/astronomer.md
> Add Astronomer

- README.md
- company-profiles/nodesource.md
> Update NodeSource's section

- README.md
- company-profiles/ably.md
> Add Ably realtime 

- README.md
- company-profiles/convert.md
> Adding Convert.com

- README.md
https://www.quantifiedcode.com/blog/quantifiedcode-shutdown
> qualified code is shutting down

- README.md
> Fixing typo in URL

- README.md
- company-profiles/thescalefactory.md
> Add The Scale Factory

- README.md
- company-profiles/sensu.md
> Add Sensu to list with company profile

- README.md
- company-profiles/stairlin.md
> Add stairlin profile

- README.md
> Adding Balsamiq

- README.md
> Adding .md extension for Balsamiq company page

- README.md
Company's website doesn't exist, and their last Twitter transmission was Jan 5, 2016.
> company no longer exists

- README.md
https://datica.com/blog/catalyze-is-now-datica/
> Catalyze is now Datica

- README.md
> Add Geckoboard to the list

- README.md
- company-profiles/codestunts.md
> added codestunts.com

- README.md
- company-profiles/britecore.md
- ~[ ] This PR contains housekeeping only (URL edits, copy changes etc)~
> Add BriteCore

- README.md
- company-profiles/humanmade.md
> Adds Human Made

- README.md
> Remove Dgraph from remote friendly companies

- company-profiles/automattic.md
Antarcia -> Antarctica
This pull request adheres to the repository's [Code of Conduct](/CODE_OF_CONDUCT.md).
> Automattic: Typo fix

- README.md
- company-profiles/codestunts.md
- company-profiles/stencil.md
Received data from Adam @ Stencil
> adding in Stencil

- README.md
- company-profiles/skillcrush.md
> Skillcrush

- README.md
- company-profiles/gaggle.md
> Added Gaggle Profile

- README.md
- company-profiles/blacktangent.md
> Add Black Tangent company profile

- README.md
- company-profiles/circonus.md
- company-profiles/consensys.md
> Add ConsenSys

- company-profiles/discourse.md
> Update employee count for Discourse

- README.md
- company-profiles/timespot.md
> adding TimeSpot

- company-profiles/mapbox.md
Edit Mapbox company size, tech, and hiring process info.
> Edit Mapbox

- README.md
- company-profiles/fuelmade.md
> Add Fuel Made

- README.md
- company-profiles/wemake-services.md
> Adds wemake.services

- README.md
- company-profiles/jitbit.md
- [*] I am an employee of the company mentioned and confirm all included details are correct
- [*] You know your alphabet - company is listed in alphabetical order in the README
- [*] The company directly hires employees. No bootcamps / freelance sites / etc
- [*] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [*] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - __Required__ for new additions. (This can be a basic outline but at least something please)
- [*] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [*] __Region__ details any restrictions to applicants …
> Added Jitbit

- README.md
- company-profiles/the-wirecutter.md
This PR will serve as a test of our shiny new Travis config :sparkles: 
After the first commit, Travis should fail because we are linking to a non-existent file from the readme.
I'll add a company profile next, which should make the tests pass again.
> Add company profile for The Wirecutter

- README.md
- company-profiles/oddball.md
> Add oddball and profile

- package-lock.json
- package.json
> Upgrade `marked` to 0.3.12

- README.md
- company-profiles/paktor.md
* Added paktor.md
* Added paktor to README.md
> Added paktor

- README.md
- company-profiles/status.md
> Add status.im

- README.md
- company-profiles/thinkful.md
> Adds Thinkful to the list

- README.md
- company-profiles/taxjar.md
> Add TaxJar

- README.md
Website says ["This company was closed in June 2017."](http://functionite.com/)
> Removed functionite.

- README.md
- company-profiles/cofense.md
See [press release](https://cofense.com/phishme-acquired-private-equity-syndicate-rebrands-cofense)
> PhishMe rebranded as Cofense

- README.md
- company-profiles/grubhub.md
> Add Grubhub

- README.md
- company-profiles/taskade.md
> added taskade company profile

- README.md
- company-profiles/dashboardhub.md
> DashboardHub company profile page added

- README.md
- company-profiles/kodify.md
interviewed there and have a friend working there
> add kodify.io

- README.md
Just adding the correct location here for our own company, which we noticed somebody else has added.
> Update location for Hanno

- README.md
- company-profiles/sandhills-development.md
> Add Sandhills Development

- README.md
- company-profiles/iopipe.md
> Add IOpipe, closes #410

- company-profiles/agilebits.md
I'm one of the hiring managers here at AgileBits, and we've got a jobs page now so I wanted it to be featured in our profile. :) I also made a few changes to the description to update it.
> Update the AgileBits profile

- company-profiles/and-yet.md
This PR updates &yet’s company profile to reflect where we are now. Thank you! ✨ 
--
> Update &yet profile

- README.md
- company-profiles/telestax.md
> Add telestax profile

- _layouts/home.html
- site/assets/companies-table.css
- site/assets/companies-table.js
This PR is intended to add very simple front-end filtering to the GitHub Pages site at https://remoteintech.github.io/remote-jobs/:
> <img src="https://user-images.githubusercontent.com/227022/40275979-eea4212e-5bc3-11e8-9e7e-779bdab01def.png" width="500">
See https://github.com/remoteintech/remote-jobs/issues/44#issuecomment-390459146 for original discussion.
> Add simple frontend filtering

- README.md
- company-profiles/duckduckgo.md
> Added info for DuckDuckGo

- README.md
- company-profiles/1password.md
We're rebranding our company to focus on 1Password, so I wanted to update this as well.
> AgileBits -> 1Password

- README.md
> Add key for what ⚠means

- .gitignore
- bin/build-site.js
- package.json
- site/coming-soon.html
Hopefully this fixes the Netlify error that has been appearing on PRs recently.  If so, this will close #422.
> Add a "Coming Soon" page to the Netlify site

- README.md
- company-profiles/drupal-jedi.md
> Added Drupal Jedi profile info.

- README.md
- company-profiles/picks-and-shovels-picksco.md
- company-profiles/picksco.md
> add picksco listing

- README.md
Changed some of the copy on the readme and moved the part about the warning ⚠️
> Readme search

- company-profiles/17hats.md
- company-profiles/evil-martians.md
- company-profiles/hack-reactor-remote.md
- company-profiles/lets-encrypt.md
- company-profiles/wolfram.md
Follow-up to https://github.com/remoteintech/remote-jobs/pull/417.
We can make the upcoming static site generator automatically detect and fill in missing sections, if desired.  In order for this to work, the sections need to be actually missing.
If there is anything similar in other company profiles, let's remove that too.
> Remove sections with no content

- company-profiles/automattic.md
Updated Automattic company size from 640+ to 750+
> FIX: Automattic company size

- README.md
- company-profiles/reaction-commerce.md
👋 Hi - I'd like to add [Reaction Commerce](https://reactioncommerce.com) to this list. We're a distributed-first company with headquarters in Santa Monica, Calif. and coworkers around the world.
> docs: add reaction-commerce.md and add Reaction Commerce to README.md

- lib/index.js
Prevent a couple more things that could potentially go wrong with readme parsing.  As far as I know, these errors have not happened yet.
> Add a couple more validation checks

- README.md
- company-profiles/hotjar.md
Added information for Hotjar from the recruitment team. I've included this information on behalf of the recruitment team at Hotjar.
> Add Hotjar information

- README.md
- company-profiles/invision.md
Primarily taken from https://www.crunchbase.com/organization/invisionapp
and from job descriptions on https://www.invisionapp.com/company#jobs
However, I do also work there.
> InVision Information

- .travis.yml
- README.md
- _layouts/default.html
- _layouts/home.html
- bin/build-site.js
- lib/index.js
- package-lock.json
- package.json
- site/README.md
- site/assets/companies-table.css
- site/assets/companies-table.js
- site/assets/company-profile.css
- site/templates/base.html
- site/templates/company.html
- site/templates/index.html
- test/fixtures/valid-incomplete/README.md
- test/fixtures/valid-incomplete/parsed-content/readme.html
- test/parsing.js
- Closes #421 (Write a static site generator in JavaScript)
- Closes #423 (Match the domain and style of the list site and blog)
Here's how it looks on my computer:
This PR should be the first successful deploy to Netlify - we will find out in a few minutes!
> Make the listing site work on Netlify

- bin/build-site.js
- bin/serve-site.js
- company-profiles/the-wirecutter.md
- lib/index.js
- package.json
- site/README.md
- site/assets/companies-table.js
- site/assets/company-profile.css
- site/assets/site.css
- site/templates/base.html
- site/templates/company.html
- test/fixtures/valid-incomplete/parsed-content/readme.html
This PR fixes #465 (mobile styles):
And some other improvements, including:
- Make it easier to work on the site locally
- Add "Edit this page on GitHub" links to each page
> Static site improvements

- site/assets/site.css
- site/templates/company.html
> Tweak spacing on company pages

- README.md
- company-profiles/black-tangent.md
> Update Black Tangent company URLs

- README.md
- company-profiles/emsisoft.md
> Add Emsisoft

- README.md
- company-profiles/realtimecrm.md
> Add realtimecrm

- company-profiles/sandhills-development.md
> Update employee count, products, and locations in the world.

- README.md
- company-profiles/equal-experts-portugal.md
> Add Equal Experts Portugal

- README.md
- company-profiles/civicactions.md
> Create CivicActions.md file

- README.md
- company-profiles/circleci.md
> Update CircleCI profile

- README.md
- company-profiles/aerolab.md
> Add Aerolab company profile

- README.md
- company-profiles/softwaremill.md
> Update softwaremill details

- company-profiles/tipe.md
> Fix typo in Tipe profile

- company-profiles/digitalocean.md
> DigitalOcean - update company size, technologies, and office locations

- company-profiles/acquia.md
> Update Acquia's company size, office locations and technologies

- README.md
- company-profiles/ombu-labs.md
Hey @nylen,
Here is a PR with my company's details. I followed your guidelines: 
Please let me know if it looks okay.
Thanks!
> Add Ombu Labs, The Lean Software Boutique, to the list

- README.md
- company-profiles/bugfender.md
- company-profiles/mobile-jazz.md
> Add Mobile Jazz and Bugfender

- README.md
- company-profiles/betapeak.md
> Added BetaPeak.

- company-profiles/kuali.md
>  Updates kuali.md to be a little more accurate

- README.md
- company-profiles/quaderno.md
> Add Quaderno to the list

- README.md
- company-profiles/webfx.md
- [ x] I am an employee of the company mentioned and confirm all included details are correct
- [x ] This PR contains housekeeping only (URL edits, copy changes etc)
- x[ ] You know your alphabet - company is listed in alphabetical order in the README
- [x ] The company directly hires employees. No bootcamps / freelance sites / etc
- [x ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x ] A [company …
> Added WebFX

- README.md
- company-profiles/shogun.md
> Added Shogun

- company-profiles/ushahidi.md
- Fix broken URL from `ushahidi.md`
- URL did not have protocol handler in the beginning,
causing it to point to a subdirectory of the directory
> Fix broken URL from ushahidi.md

- company-profiles/1password.md
- Update URL address to the new working URL,
since the old address was getting redirected to the blog front page.
-----
> Update 1password.md with the new URL address

- README.md
- company-profiles/scopic-software.md
Let's have Scopic Software, the world's largest virtual company in the list!
_Company blurb_
Custom solutions for virtually everything. The world’s largest virtual company. We create custom solutions for virtually everything! Our passion is developing visually engaging and interactive solutions, custom made to enhance your business. Over a decade of service and 1000+ projects, developing digital products and user-centric software for a wide range of industries and niches including: Manufacturing, Music and film, Fintech, Food and Fitness, Healthcare and Gaming.
_Company size_
200+ number of Scopic team members.
_Remote status_
We are a fully remote company, with our team member located in 30+ countries.
_Company technologies_
WEB FRAMEWORKS
We turbocharge our development process with …
> Add Scopic Software to the list

- README.md
- company-profiles/lambda-school.md
> Lambda School

- README.md
- company-profiles/adzuna.md
Signed-off-by: Vangelis Katsikaros <vkatsikaros@gmail.com>
> Add Adzuna to the list

- README.md
- company-profiles/beyondpricing.md
> Add BeyondPricing

- company-profiles/reactiveops.md
> Update ReactiveOps details

- README.md
- company-profiles/research-square.md
> Update Research Square details

- README.md
- company-profiles/over.md
- [x ] You know your alphabet - company is listed in alphabetical order in the README
> Add Over to List

- company-profiles/over.md
> Remove example regions from Over

- README.md
- company-profiles/next.md
> Clankford patch 1

- README.md
- company-profiles/tuft-and-needle.md
> Add Tuft & Needle

- README.md
- company-profiles/grou-ps.md
> added Grou.ps

- Aula.md
The pull request adheres to the repository's Code of Conduct ✅
If the company is at least partially remote ✅
If you add the company in alphabetical order in the list ✅
If you submit the company with a website ✅
If you submit the company with the regions that are accepted for remote positions (for more details see the instructions in the example company profile) ✅
If you submit a company profile page and link the company name to it (see example here) ✅
> Added Aula.md

- README.md
- company-profiles/four-kitchens.md
> Updating Four Kitchens profile.

- README.md
- company-profiles/servmask.md
> Add ServMask

- company-profiles/github.md
:wave:
- Updated number of users
- Updated number of repos
- Updated number of employees
- Added Go as a technology
---
> Update some of GitHub's data

- README.md
- company-profiles/renofi.md
Thanks for compiling and maintaining this resource! This PR adds [RenoFi](https://www.renofi.com/), a fully-distributed team.
> Adding RenoFi

- README.md
- company-profiles/ios-app-templates.md
- company-profiles/iosapptemplates.md
> Add iosapptemplates.com jobs

- README.md
- company-profiles/compucorp.md
> Add Compucorp

- README.md
- company-profiles/15five.md
we are hiring people in central / south america now too.
> update 15five region

- README.md
- company-profiles/theorem.md
> Add Theorem

- README.md
- company-profiles/interview-schedule.md
> Add Interview Schedule

- PULL_REQUEST_TEMPLATE.MD
- README.md
- company-profiles/connexa.md
> Fix Connexa apply link

- company-profiles/axelerant.md
> corrected link for axelerant - fixes half of #528

- README.md
- company-profiles/trussworks.md
> Add TrussWorks.

- README.md
- company-profiles/btownweb.md
> adding company profile for BTownWeb

- company-profiles/recharge.md
> Fix dead apply link of ReCharge.

- company-profiles/platform-sh.md
> Update 'How to apply' section of platform.sh.

- README.md
- company-profiles/spoqa.md
> Update Spoqa information

- README.md
- company-profiles/abiturma.md
> Add entry and profile for abiturma (Ger)

- README.md
- company-profiles/blameless.md
> Add Blameless Company Profile

- company-profiles/mixmax.md
> Update mixmax.md with current information

- company-profiles/softwaremill.md
I'm not an employee, but this is clearly explained in each job description https://softwaremill.com/join-us/
> update to add Polish language requirement

- README.md
- company-profiles/balena.md
Change-type: patch
Signed-off-by: Chris Crocker-White <chriscw@balena.io>
> Add balena

- README.md
- company-profiles/headway.md
> Add profile for Headway

- README.md
- company-profiles/cloudapp.md
> Add CloudApp

- README.md
- company-profiles/optoro.md
> Add Optoro

- README.md
Current information is wrong. They only approve developers from anywhere in the USA or Canada.
https://boards.greenhouse.io/algorithmia/jobs/4063489002?gh_jid=4063489002
> Updates algoritmia info

- README.md
- company-profiles/darecode.md
> darecode.md

- README.md
- company-profiles/influxdata.md
> Update profile for InfluxData

- lib/index.js
- test/validation-errors.js
This PR will make bot error messages like https://github.com/remoteintech/remote-jobs/pull/632#issuecomment-541516829 a bit clearer. Also I want my Hacktoberfest tshirt too.
> Update bot messages

- README.md
- company-profiles/iclinic.md
> add iclinic

- README.md
- company-profiles/evrone.md
> Evrone company description

- README.md
- company-profiles/wallethub.md
> added company profile for wallethub and link in readme.md

- README.md
- company-profiles/instamobile.md
> Add instamobile reference

- README.md
- company-profiles/docker.md
> Add Docker

- README.md
- company-profiles/hanno.md
> Extend company profile Hanno

- README.md
- company-profiles/filament-group.md
> Add Filament Group

- company-profiles/toggl.md
> Change toggl info

- README.md
- company-profiles/trello.md
> Add data to Trello entry

- README.md
- company-profiles/rebelmouse.md
- company-profiles/webdevstudios.md
> Add webdevstudios

- README.md
- company-profiles/rebelmouse.md
> Add rebel mouse

- README.md
- company-profiles/privacycloud.md
> Add PrivacyCloud

- README.md
- company-profiles/datastax.md
> Add DataStax listing 

- README.md
- company-profiles/x-team.md
> Add X-team info

- README.md
- company-profiles/komoot.md
> added Komoot in remote companies list

- README.md
- company-profiles/functionize.md
> add Functionize

- README.md
- company-profiles/bizink.md
- company-profiles/rebelmouse.md
- company-profiles/webdevstudios.md
> Add bizink

- README.md
- company-profiles/cabify.md
> Issue # 575: Add cabify company to the list

- README.md
- company-profiles/bizink.md
- company-profiles/graylog.md
- company-profiles/rebelmouse.md
- company-profiles/webdevstudios.md
> Add graylog

- README.md
Knack's previous domain was knackhq.com and was switched to knack.com
> Update Knack URL to current domain

- README.md
- company-profiles/bairesdev.md
> Add Bairesdev company

- company-profiles/evil-martians.md
Proper name, office locations, blurb, technologies
> Update Evil Martians company info

- README.md
- company-profiles/gitbook.md
> Update gitbook desc

- lib/index.js
- package-lock.json
- package.json
- test/fixtures/valid-incomplete/parsed-content/10up.howToApply.html
- test/fixtures/valid-incomplete/parsed-content/18f.howToApply.html
- test/fixtures/valid-incomplete/parsed-content/readme.html
- test/validation-errors.js
Update all npm (JavaScript) dependencies to their latest versions.
> Update npm packages

- README.md
- company-profiles/bebanjo.md
> Add company info for Bebanjo

- README.md
- company-profiles/joyent.md
> Add Joyent

- README.md
- company-profiles/octopus-deploy.md
> added octopus deploy

- README.md
- company-profiles/third-iron.md
> Add Third Iron

- README.md
- company-profiles/smugmug.md
Adds extra context to SmugMug’s listing, adhereing to the Contributing Guidelines and Code of Conduct.
I am the co-founder, CEO & Chief Geek at SmugMug. We love remote workers.
> Improve SmugMug’s company blurb

- company-profiles/xapo.md
> Update xapo profile

- README.md
- company-profiles/aestudio.md
> Add AE Studio

- README.md
- company-profiles/mediavine.md
> Added information for remote jobs at Mediavine

- README.md
- company-profiles/bairesdev.md
- company-profiles/carbon-black.md
> Add company info for Carbon Black 

- README.md
- company-profiles/heetch.md
--- 
Hello, I've added the company I'm working for, we're about 80 engineers working remotely :)
> Add Heetch

- README.md
- company-profiles/beenverified.md
- company-profiles/lifetime-value-company.md
> Add BeenVerified, LTV

- README.md
- company-profiles/metamask.md
> Add MetaMask

- README.md
- company-profiles/guidesmiths.md
> Add GuideSmiths

- README.md
- company-profiles/impala.md
> Add Impala

- README.md
- company-profiles/codeship.md
> added geographical information for Codeship

- README.md
- company-profiles/rainforest-qa.md
* Add company info for RainforestQA
* Remove ⚠️️ from README.md
> Add company info for RainforestQA

- README.md
- company-profiles/fentime.md
> add company of fentime.

- README.md
- company-profiles/mailerlite.md
> adding info for mailerlite to list

- README.md
- company-profiles/epam.md
> proposal to add EPAM company

- README.md
- company-profiles/earthofdrones.md
> Add EarthOfDrones company profile

- company-profiles/alice.md
Added link to an article by ALICE VP of Engineering that describes with a lot of details how ALICE remote-first culture is.
> Added link to article that describes ALICE's culture in detail

- README.md
- company-profiles/chroma.md
> Add Chroma

- README.md
- company-profiles/implisense.md
> Add Implisense

- README.md
- company-profiles/ergeon.md
> created company profile

- README.md
- company-profiles/smartcash.md
> Add SmartCash as a company

- README.md
- company-profiles/logdna.md
> add logdna details & fix data science brigade url

- README.md
- company-profiles/scrapingbee.md
> Add Scrapingbee

- README.md
- company-profiles/pagepro.md
> pagepro company profile

- README.md
- company-profiles/vast-limits.md
> Added vast limits

- README.md
- company-profiles/gremlin.md
> Add Gremlin, a reliability through chaos engineering company

- README.md
- company-profiles/plai.md
> Added Plai (plai.team)

- README.md
- company-profiles/homevalet.md
> Add HomeValet

- README.md
- company-profiles/ghost-inspector.md
> adds Ghost Inspector

- README.md
- company-profiles/abstract.md
- company-profiles/bonsai.md
> Added Bonsai & Abstract

- README.md
- company-profiles/cueup.md
> Added Cueup

- README.md
- company-profiles/ipinfo.md
> Added IPInfo 

- README.md
- company-profiles/wizeline.md
> Add Wizeline

- README.md
- company-profiles/grafana.md
> - Adds Grafana Labs to the list

- README.md
- company-profiles/capchase.md
> Add Capchase company

- README.md
- company-profiles/predict-mobile.md
> Added Predict Mobile

- README.md
> Update rtCamp location

- README.md
- company-profiles/pathable.md
- Updates Pathable profile.
- Removes emoji from readme.
> Adds Pathable information. #639

- README.md
- company-profiles/cards-against-humanity.md
> Added Cards Against Humanity info

- README.md
- company-profiles/cartstack.md
> Updated cartstack.md

- README.md
- company-profiles/truelogic.md
> Add truelogic

- README.md
- company-profiles/audiense.md
> Added Audiense.md

- README.md
- company-profiles/parsely.md
- Updates Parse.ly profile.
- Removes emoji from readme.
> Adds Parse.ly information. #639

- README.md
- company-profiles/cards-against-humanity.md
- company-profiles/help-scout.md
> Updated Help Scout

- README.md
- company-profiles/wikihow.md
- [] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
> Page wikihow

- README.md
- company-profiles/vercel.md
> add Vercel.

- README.md
- company-profiles/collabora.md
> Updated collabora.md

- README.md
- company-profiles/bright-funds.md
> Updated bright-funds.md

- README.md
- company-profiles/bluespark.md
- company-profiles/wikihow.md
> updated company profile-Bluespark

- README.md
- company-profiles/honeybadger.md
> Updated Honeybadger

- README.md
- company-profiles/youcanbook-me.md
- [X ] This PR contains housekeeping only (URL edits, copy changes etc)
> Youcanbook.me company information updated

- README.md
- company-profiles/khan-academy.md
- [] This PR contains housekeeping only (URL edits, copy changes etc)
- [√] You know your alphabet - company is listed in alphabetical order in the README
- [√] The company directly hires employees. No bootcamps / freelance sites / etc
- [√] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [] A [company …
> Update Khan Academy Region To USA

- README.md
- company-profiles/fivexl.md
> add FivexL

- README.md
- company-profiles/whitecap-seo.md
> Update Whitecap SEO company information

- README.md
- company-profiles/varnish-software.md
> Update Varnish Software company information

- README.md
This PR fixes #523. I changed all instances of "US" and "United States" in README to "USA". 
> Updating US and United States to USA

- README.md
- company-profiles/mixcloud.md
> Added information on MixCloud

- README.md
- company-profiles/healthfinch.md
> Updated healthfinch.md

- README.md
- company-profiles/metalab.md
> Adding info for Metalab

- README.md
- company-profiles/stitch-fix.md
> Updated stitch-fix.md

- README.md
- company-profiles/skillshare.md
> added Skillshare

- README.md
- company-profiles/checkly.md
> add checkly

- README.md
- company-profiles/oreilly-media.md
> Adding info for O'Reilly Media

- README.md
- company-profiles/mozilla.md
> Add info for Mozilla

- README.md
- company-profiles/npm.md
- [] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
#639
> Update Information for npm

- README.md
- company-profiles/kaggle.md
- company-profiles/wells-fargo.md
> adds wells fargo

- README.md
- company-profiles/upwork-pro.md
> Added upwork-pro information

- README.md
- company-profiles/real-digital.md
> Add real.digital

- README.md
- company-profiles/koding.md
> Updated Koding company information

- README.md
- company-profiles/bluespark.md
- company-profiles/codeship.md
> Update Codeship company information

- company-profiles/real-digital.md
Just a small fix after a talk with HR
---
> Fix real-digital location
