remoteintech/remote-jobs

README.md

HashiCorp is distributed across the United States (not yet international): https://www.hashicorp.com/jobs.html

Add HashiCorp to remote-friendly jobs

---

README.md

This PR adds `cartodb.com` to the list. An example of a remote job offer: https://cartodb.com/jobs/junior-designer.

Adds CartoDB

---

README.md
company-profiles/github.md

This branch adds a company profile for GitHub and fills out the empty columns in the GitHub row of the README!
:heart::yellow_heart::green_heart::blue_heart::purple_heart:

Add GitHub company profile

---

README.md

- It could be automated later (e.g. in gh-pages branch).
- It leads to a number of potential conflicts at the moment ([#58](https://github.com/jessicard/remote-jobs/pull/58/files#diff-04c6e90faac2675aa89e2176d2eec7d8R3), [#59](https://github.com/jessicard/remote-jobs/pull/59/files#diff-04c6e90faac2675aa89e2176d2eec7d8R3), [#60](https://github.com/jessicard/remote-jobs/pull/60/files#diff-04c6e90faac2675aa89e2176d2eec7d8R3)).
- It could easily be out of date.
- It is not that useful, you could just scroll through the list.

Remove number of brands from the README

---

README.md

wordpress.com is run by Automattic (already on the list) and isn't a separate company.
WordPress, however, is fantastic software built buy hundreds of volunteers from around the world. :D

Remove "Wordpress" from company list

---

README.md

Their main office is in the bay area, with remote supported primarily for security specialists / coding

add threatstream

---

README.md

URL changes. 
I'm not 100% about Skillshare, I think the job posting on WeWorkRemotely, as pulled in through @whatasunnyday's script in #40 is actually about teaching jobs rather than working for Skillshare in the team.

amend skillshare and 112 links

---

README.md
company-profiles/hackreactorremote.md

Hack Reactor Remote Beta is a 3-month coding bootcamp that trains software engineers in a remote environment. **Hack Reactor Remote Beta also hires remote employees!**
I listed "Pacific Time Zone (PT)," as it is the generic, official name that covers both PST and PDT.
https://en.wikipedia.org/wiki/Pacific_Time_Zone

Add Hack Reactor Remote Beta

---

README.md

SocialBro have changed their name, now they call Audiense. I'm not an employee actually but I have been in the past.

SocialBro now is Audiense

---

README.md
company-profiles/helabs.md

Adding HE:labs to this awesome list 😄 

Add helabs

---

README.md
company-profiles/thegrid.md

This PR adds The Grid's company profile, and adds the region to the existing readme file.

add the grid profile and edit existing readme

---

README.md
company-profiles/laterpay.md

This company was already in the list but with no profile
-----

Add LaterPay company profile

---

PULL_REQUEST_TEMPLATE.MD

I've copied the modified PR template below.  Compare its links against other recent PRs:  they work here, but point to broken pages like https://github.com/CODE_OF_CONDUCT.md elsewhere.
---

Fix broken links in PR template

---

README.md

Add link to the grid profile in readme.md

---

README.md
bin/validate.js

This PR makes some changes to validate the sort order of companies in the readme.
As with https://github.com/remoteintech/remote-jobs/pull/378, it should fail at first because the existing data doesn't pass the new validation, then I'll make another commit to clean things up.

Validate company sort order in readme; try out comment bot

---

README.md
company-profiles/algorithmia.md

Add Algorithmia

---

PULL_REQUEST_TEMPLATE.MD
README.md
company-profiles/nuna.md

Please note, I did not check "This PR contains housekeeping only (URL edits, copy changes etc)" because I would like to submit a new company profile, not update an existing one.  Hope that's correct.
- [] This PR contains housekeeping only (URL edits, copy changes etc)

Add Nuna Inc to listing of remote jobs

---

company-profiles/gitlab.md

Add GitLab company details

---

company-profiles/geckoboard.md

Update geckoboard region to just "Worldwide"

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.MD
company-profiles/example.md

Updating the rules on the region section for contributing company information as per #485

Update region guidelines

---

README.md
company-profiles/betterup.md

Add BetterUp to the list of remote companies

---

lib/index.js
test/validation-errors.js

Improves the error message from https://github.com/remoteintech/remote-jobs/pull/519#issuecomment-451965196:
```diff
-etch.md: Expected filename "basecamp.md" for company "Basecamp"
+etch.md: Company title "Basecamp" doesn't match filename (expected ~ "basecamp.md")
```

Improve error message for filename/title mismatch

---

company-profiles/basecamp.md

- Update number of team members based on company's Team page
- Add URL of the jobs page to point towards https://basecamp.com/about/jobs
- Update `basecamp.md` with the direct URL for team page
- URL structure of the company site had changed,
and this points to the right URL path

Update basecamp.md details

---

README.md
company-profiles/giant-swarm.md

Add company profile for Giant Swarm

---

company-profiles/oddball.md

update broken link url to current hiring page

---

company-profiles/trussworks.md

This is a housekeeping update to add the jobs URL not included in #583. I hid the rest of the checklist, but if you prefer it displayed please feel free to uncomment it. :)
- - -

add jobs link to TrussWorks company blurb

---

README.md
company-profiles/roadtrippers.md

feat: add Roadtrippers as another company that hires remotely

---

bin/build-site.js

Current PRs are failing to build. The remoteintech.company site pulls the CSS rules from the WP.com site, and this is failing because the WP.com site now includes a stylesheet URL without a protocol:
```
//widgets.wp.com/wpcom-block-editor/common.min.css?ver=20190930180734
```
To fix this, we'll add `https:` to the front of any such links.

Fix the site build on Netlify

---

README.md
company-profiles/betable.md

Add company info for betable

---

site/assets/site.css

Before this PR, the links to GitHub and Twitter can look a bit weird if only one of them has been visited, since the one that has been visited will show up in red instead of white.
After this PR they will always show up in white.

Make footer social links always white

---

README.md
company-profiles/formidable.md

Add Formidable to Remote Jobs

---

company-profiles/trussworks.md

TrussWorks: Update company size and technologies

---

bin/build-site.js
bin/validate.js
lib/index.js
package-lock.json
package.json
site/assets/companies-table.js
site/assets/site.css
site/templates/base.html
test/fixtures/duplicate-company/README.md
test/fixtures/duplicate-company/company-profiles/10up.md
test/fixtures/duplicate-company/company-profiles/17hats.md
test/fixtures/duplicate-company/company-profiles/18f.md
test/fixtures/duplicate-company/company-profiles/and-yet.md
test/fixtures/duplicate-company/company-profiles/and.md
test/fixtures/valid-incomplete/parsed-content/readme.html
test/lib/index.js
test/validation-errors.js
test/validation-script.js

This pull request modifies the "filter" box on the list homepage to search through all company profile data.
You can read more about how the search works here: https://blog.remoteintech.company/search-help/ This page is also linked from the "More info" text at the search box.
- Closes #584
- Closes #462 (search for `_incomplete` as mentioned in the search documentation)
- Workaround/alternative to multiple other requested enhancements including #464, #485, #569
You can try this before it's merged by going here: https://deploy-preview-763--remote-jobs.netlify.app/ Please let me know if you see any issues.

Add full profile search

---

README.md
company-profiles/adaface.md

All details from sample company profile are added

Adding new company profile of Adaface

---

README.md
company-profiles/seaplane.md

Add remote work entry for Seaplane

---

README.md
company-profiles/mongodb.md

feature: add MongoDB company profile

---

README.md
company-profiles/amazon.md

added Amazon with links to remote opportunities landing page

---

README.md

The Linux Foundation was missing the region.
- [X ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.

edit Linux Foundation - add region

---

README.md
company-profiles/seeq.md

add new company - Seeq

---

lib/index.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

company-profiles/cards-against-humanity.md

Add's a link to the Cards Against Humanity Careers page and expands the blog URL linked text for accessibility.

Add Cards Against Humanity Careers page link

---

README.md
company-profiles/accor.md

add new company - Accor

---

README.md
company-profiles/renaissance.md

Add new company: Renaissance

---

README.md
company-profiles/launch-potato.md

This company came from issue #1685, referencing the comment in issue #772.

add new company - Launch Potato

---

site/assets/companies-table.js

Updated the setupSearch function for #1736

---

lib/index.js

Enhanced URL handling in `index.js`:
- Added checks in `getUrlInfo` for malformed URLs.
- Refined `extractMainDomainFromUrl` for better domain extraction.
- Ensured external links apply target attributes correctly.
- Improved logging to simplify debugging.
This PR includes housekeeping improvements to URL handling in the script, following the guidelines in [CONTRIBUTING.md].

Improve URL handling for external links in index.js
