- README.md
- company-profiles/happy-cog.md
> Updated Happy Cog company information

- README.md
- company-profiles/focusnetworks.md
> Add Focusnetworks info

- README.md
- company-profiles/continu.md
> Updated Continu company information

- README.md
- company-profiles/core-apps.md
> Updated Core-Apps.md

- company-profiles/zapier.md
I work at Zapier. We're actually over 350 people, but have just 302 listed on our "about" page, so I've updated this to say 300+
Thanks for providing this resource!
> Update number of employees for Zapier

- README.md
- company-profiles/brave-investments.md
> brave-investments

- company-profiles/platform-builders.md
> Fix markdown link

- README.md
- company-profiles/delighted.md
- company-profiles/evelo.md
> added delighted company profile

- README.md
- company-profiles/scrapinghub.md
> Add info for Scrapinghub

- README.md
- company-profiles/opencraft.md
> Add Opencraft info

- README.md
- company-profiles/test-double.md
> Test double

- README.md
- company-profiles/vox-media.md
> added Vox Media

- README.md
- company-profiles/travis-ci.md
> Travis branch

- README.md
- company-profiles/linaro.md
> DOC: edit Linaro

- README.md
- company-profiles/fire-engine-red.md
> added Fire Red Engine

- README.md
- company-profiles/brave-investments.md
- company-profiles/compose.md
- company-profiles/core-apps.md
- company-profiles/sweetrush.md
- company-profiles/zapier.md
> Updating Taplytics.md and Recurly.md

- README.md
- company-profiles/toast.md
> Adding Toast

- README.md
- company-profiles/idonethis.md
> Fix idonethis

- README.md
- company-profiles/marketade.md
> Updating marketade.md

- README.md
- company-profiles/episource.md
> Add Episource

- README.md
- company-profiles/coreos.md
> Updated details for CoreOS

- README.md
- company-profiles/designcode.md
> Adding designcode 

- README.md
- company-profiles/scandit.md
> Adding company profile for Scandit

- README.md
- company-profiles/sutherland-cloudsource.md
> Details company profile Sutherland

- README.md
- company-profiles/interpersonal-frequency-i-f.md
> Added Interpersonal Frequency company info

- company-profiles/Mozzila.md
> added mozzila

- README.md
- company-profiles/mysql.md
> Add mysql.md

- README.md
- company-profiles/travis.md
> Add Travis - travistravis.co

- README.md
- company-profiles/peopledoc.md
> update peopledoc to fix pr991

- README.md
- company-profiles/epic-games.md
> add: epic games company profile to README.md

- README.md
- company-profiles/engineyard.md
Hi, I added info for Engine Yard based on what I've found online. Hope this can still be helpful.
> added Engine Yard company info and updated README.md

- README.md
- company-profiles/soostone.md
> Added region of Soostone in README.md

- README.md
- company-profiles/gohiring.md
Thank you! I have updated the company information for GoHiring.
- [x ] This PR contains housekeeping only (URL edits, copy changes etc)
> Updated GoHiring company information

- README.md
- company-profiles/estately.md
Please accept this pull request.
> Added the details of Estately

- README.md
- company-profiles/bill.md
> feat(bill-company):  add bill company profile

- README.md
- company-profiles/shopify.md
- package-lock.json
> Added Shopify

- README.md
- company-profiles/yandex.md
> add yandex

- README.md
- company-profiles/procenge.md
> Infoprocenge

- README.md
- company-profiles/teleport.md
> Updated teleport.md

- README.md
- company-profiles/salesforce.md
> Updated salesforce file with new information

- README.md
- company-profiles/flowing.md
> Adds Flowing

- README.md
- company-profiles/jayatech.md
> Add Jayatech

- README.md
- company-profiles/mux.md
> Add Mux.com

- README.md
- company-profiles/memberful.md
- company-profiles/our-hometown-inc.md
> Add info for Memberful

- README.md
- company-profiles/impira.md
> Added Impira

- README.md
- company-profiles/modsquad.md
> Added modsquad

- README.md
- company-profiles/particular-software.md
> Updated Particular Software details

- README.md
- company-profiles/gotsoccer, llc.md
> Added information about Got Soccer

- company-profiles/envato.md
- Sync company blurb with their about page
- Update company size
- Add new offices
- Add technologies used as per updated profile template
> Update details for Envato

- company-profiles/flowing.md
If updating or adding a company, please include details here: fixes some typos and added some newlines to avoid content being rendered in one line
> [edit Flowing company]: fixes some typos and rendering issues

- README.md
- company-profiles/skyrocket-ventures.md
> added a new company profile called skyrocket ventures

- README.md
- company-profiles/uhuru.md
This was meant to close #889 but it seems @dougaitken closed it a couple of minutes ago...Sorry if this is just adding noise.
> Adding New Company - Uhuru

- company-profiles/mux.md
> edit Mux company

- README.md
- company-profiles/codesandbox.md
> add new company - CodeSandbox

- README.md
Adding the region to IOS App Templates - it was missing
> edit IOS App Templates - add region

- README.md
If updating or adding a company, please include details here: The region was missing for LaterPay so it was added.
> edit LaterPay - add region

- README.md
If updating or adding a company, please include details here: The region was missing for RebelMouse so it was added.
> edit RebelMouse - add region

- company-profiles/automattic.md
Update Automattic for Oct 2020 to update employee and country count, rewrite content.
> edit Automattic

- README.md
- company-profiles/tractionboard.md
> Added a new company profile TractionBoard

- README.md
- company-profiles/sysdig.md
If updating or adding a company, please include details here: Updated Sysdig.md under company-profiles since core information were missing.
> Sysdig information updated. Has all necessary info on sysdig.md

- README.md
- company-profiles/keen-io.md
> Added information about Keen io

- README.md
- company-profiles/microsoft.md
> Add company - Microsoft

- README.md
- company-profiles/precision-nutrition.md
- [:heavy_check_mark:] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [:heavy_check_mark:] The company directly hires employees. No bootcamps / freelance sites / etc
- [:heavy_check_mark:] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [:heavy_check_mark:] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - This is __required__ for new additions.
- …
> Update Precision Nutrition

- README.md
- company-profiles/ollie.md
> Add new company - Ollie

- README.md
- company-profiles/tenable.md
- company-profiles/the-publisher-desk.md
> Edit The Publisher Desk company

- README.md
- company-profiles/activecampaign.md
> Added ActiveCampaign Company.

- README.md
- company-profiles/surevine.md
- [:heavy_check_mark:] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [:heavy_check_mark:] The company directly hires employees. No bootcamps / freelance sites / etc
- [:heavy_check_mark:] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [:heavy_check_mark:] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - This is __required__ for new additions.
- …
> Edit Surevine

- README.md
- company-profiles/fingerprintjs.md
If updating or adding a company, please include details here: adding [FingerprintJS](https://fingerprintjs.com)
> Add new company - FingerprintJS

- README.md
- company-profiles/leadfeeder.md
> Add new company - Leadfeeder

- .github/workflows/ci.yml
- .travis.yml
Resolves https://github.com/remoteintech/remote-jobs/issues/541.
This is a migration from TravisCI to Github Actions to run validation and tests.
> Add GitHub Actions integration for validation and tests

- README.md
- company-profiles/reboot-studio.md
> add new company - Reboot Studio

- README.md
- company-profiles/reducer.md
- [x ] I am an employee of the company mentioned and confirm all included details are correct.
- [x ] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [x ] The company directly hires employees. No bootcamps / freelance sites / etc
- [x ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [x ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - This is __required__ for new additions.
- [x ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x ] __Region__ details the geographic regions in which this company's employees can reside. For …
> add new company - Reducer

- README.md
- company-profiles/jbs-custom-software-solutions.md
If updating or adding a company, please include details here: Added JBS Custom Software Solutions
> Add new company - JBS Custom Software Solutions

- README.md
- company-profiles/outsourcingdev.md
add new company - OutsourcingDev
If updating or adding a company, please include details here: add new company - OutsourcingDev
> add new company - OutsourcingDev

- README.md
> Fix Microsoft url

- README.md
- company-profiles/scylladb.md
- [ x] I am an employee of the company mentioned and confirm all included details are correct.
- [ x] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [ x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [ x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/master/company-profiles/example.md) is included - This is __required__ for new …
> add scylladb

- README.md
- company-profiles/remote-garage.md
- company-profiles/remotegarage.md
> Add Remote Garage

- README.md
- company-profiles/veryfi.md
If updating or adding a company, please include details here: added veryfi.com
> Add new company - Veryfi

- README.md
- company-profiles/yazio.md
> Add YAZIO company

- README.md
- company-profiles/pnc-financial-services.md
📝Add new company - PNC Financial Services
> Add new company - PNC Financial Services

- README.md
- company-profiles/entrision.md
> add new company - Entrision

- README.md
- company-profiles/journy-io.md
> Add new company - journy.io

- README.md
- company-profiles/merico.md
1. Code deep analysis engine: **Merico** believe the software development process and developer competence are reflected in developer contribution to software projects.
2. Remote DNA.
---
> add new company - Merico

- README.md
- company-profiles/serpapi.md
📝Add new company - SerpApi
---------------------------------------------------------------------------------------------------
> Add new company - SerpApi

- README.md
- company-profiles/airtreks.md
> Added AirTreks Company.

- README.md
- company-profiles/fmx.md
> add new company - FMX

- README.md
- company-profiles/chatgen.md
> Add new company - ChatGen

- README.md
- company-profiles/boldare.md
Add new company - [Boldare](https://boldare.com)
> Add new company - Boldare

- README.md
- company-profiles/konkurenta.md
I'd like to add _Konkurenta_ to the list ✌️
I'd say, our main benefit is our stack (Javascript, React, React Native, Graphql, WebRTC, Node.js, RabbitMQ, MongoDB, MySQL, Redis) and friendly, ambitious team (family) 🚀
> Add new company - Konkurenta

- README.md
- company-profiles/epilocal.md
> Add new company - Epilocal

- README.md
- company-profiles/datacamp.md
> Add new company - DataCamp

- README.md
- company-profiles/aivitex.md
> add new company - AIVITEX

- README.md
- company-profiles/smile.md
> Add new company - smile.io

- README.md
- company-profiles/calamari.md
> Add Calamari

- README.md
- company-profiles/1password.md
> Edit 1Password company

- README.md
- company-profiles/ambaum.md
> Edit BTown Web is now Ambaum

- README.md
- company-profiles/beyondpricing.md
> Edit BeyonPricing

- README.md
- company-profiles/exportdata.md
📝 Add new company - ExportData
-------------------------
> Add new company - ExportData

- README.md
- company-profiles/quora.md
Add New Company - [QUORA](https://www.quora.com/)
Closed #1139 
> Add new company - Quora

- README.md
- company-profiles/liveperson.md
> Add new company - LivePerson

- company-profiles/liveperson.md
> edit LivePerson company

- README.md
- company-profiles/ebsco-information-services.md
- [❌] **N/A** This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [✔️] I am an employee of the company mentioned and confirm all included details are correct.
- [✔️] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [✔️] The company directly hires employees. No bootcamps / freelance sites / etc
- [✔️] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [✔️] A [company …
> Added EBSCO Information Services to list of companies.

- README.md
- company-profiles/labelbox.md
> Add new company - Labelbox

- README.md
- company-profiles/pex.md
- [x ] I am an employee of the company mentioned and confirm all included details are correct.
> Add new company - Pex

- README.md
- company-profiles/appwrite.md
> Add new company - Appwrite

- README.md
- company-profiles/kentik.md
> Add new company - Kentik

- README.md
- company-profiles/paytm-labs.md
> Add new company - Paytm Labs

- README.md
- company-profiles/netris.md
> Added Netris.ai

- README.md
- company-profiles/taledo.md
> [add new company - Taledo]

- README.md
- company-profiles/parabol.md
If updating or adding a company, please include details here: add new company - Parabol.
> add new company - Parabol

- README.md
- company-profiles/flightaware.md
> add new company - FlightAware

- README.md
- company-profiles/lambert-labs.md
If updating or adding a company, please include details here: Adding Lambert Labs
> Add new company - Lambert Labs

- README.md
- company-profiles/fraudio.md
> Add new company - FRAUDIO

- README.md
- company-profiles/fireball-labs.md
If updating or adding a company, please include details here: adding company Fireball Labs
- [ x The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
> add new company - Fireball Labs

- README.md
- company-profiles/fatmap.md
If updating or adding a company, please include details here: adding company FATMAP
> add new company - FATMAP

- README.md
- company-profiles/vshn.md
> Add new company - VSHN AG

- README.md
- company-profiles/panther-labs.md
> add new company - Panther Labs

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- PULL_REQUEST_TEMPLATE.MD
- README.md
- bin/build-site.js
- site/README.md
> Update references of master to main

- package-lock.json
> update package-lock hopefully?

- README.md
- company-profiles/session.md
> Add new company - Session

- README.md
- company-profiles/tatvasoft.md
> add new company - TatvaSoft

- README.md
This pull request is used to fix the type on README.md, e.g. not add/updating company
> Update README.md's typo from `pull  reqest` to `pull request`

- README.md
- company-profiles/teamflow.md
> add new company - Teamflow

- README.md
- company-profiles/polygon.md
> Add new company - Polygon

- README.md
- company-profiles/lionsher.md
> Add new company - LionSher

- README.md
- company-profiles/twilio.md
> add new company - Twilio

- README.md
- company-profiles/algorand.md
> Add new company - Algorand

- README.md
- company-profiles/okta.md
> Add new company - Okta

- README.md
- company-profiles/coinbase.md
> Add new company - Coinbase

- README.md
- company-profiles/axios.md
> add Axios company

- company-profiles/yodo1.md
📝Title your pull request descriptively. `Fix yodo1 broken link`
Issue: https://github.com/remoteintech/remote-jobs/issues/528
> yodo1 broken link update

- README.md
- company-profiles/andela.md
> Add new company - Andela

- company-profiles/line-plus-corporation.md
Hello.
I updated remote status of LINE Plus Corporation according to new work practices of LINE.
You can check out [the news from the official site](https://linepluscorp.com/pr/news/ko/2021/3791) 
(by the way it is written in Korean).
> Edit remote status of LINE Plus Corporation

- README.md
- company-profiles/capital-one.md
- [ x ] I am an employee of the company mentioned and confirm all included details are correct.
- [ x ] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [ x ] The company directly hires employees. No bootcamps / freelance sites / etc
- [ x ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [ x ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for …
> creating company page for Capital One

- README.md
- company-profiles/fairwinds.md
> Add new company - Fairwinds Ops

- README.md
- company-profiles/madewithlove.md
> Edit madewithlove company

- README.md
- company-profiles/no-code-no-problem.md
> add new company - No Code No Problem

- README.md
- company-profiles/uncapped.md
> Add new company - Uncapped

- lib/index.js
In https://github.com/remoteintech/remote-jobs/pull/1335 the `marked` dependency was updated and it broke the build. It seems things were updated so that where previously you parsed markdown with calls directly to `marked` you now need to use `marked.parse` instead. This updates those calls.
> Fix calls to marked calls after depencency update

- README.md
- company-profiles/streamnative.md
> Add new company - StreamNative

- README.md
- company-profiles/voiio.md
> add new company - voiio

- README.md
- company-profiles/socket-supply-co.md
> Add New Company - Socket Supply Co.

- README.md
- company-profiles/shareup.md
> Add new company - Shareup

- README.md
- company-profiles/appinio.md
> add new company - Appinio

- company-profiles/evil-martians.md
Hey. Updated some details, updated offices and tech. Updated instructions on how to apply as well.
> Update: Evil Martians

- company-profiles/iterative.md
> [edit Iterative company] - adjusting lever source label

- README.md
- company-profiles/intuition-machines-inc.md
- [ x The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
> Add new company - Intuition Machines, Inc

- company-profiles/pleo.md
2022 Tech, company size updates + housekeeping
> Edit Pleo company

- README.md
- company-profiles/kona.md
> Add new company - Kona

- README.md
- company-profiles/deskpass.md
Signed-off-by: Tim Shaw <tim@deskpass.com>
> Add new company - Deskpass

- README.md
- company-profiles/kea.md
📝Title your pull request descriptively. `[edit X company]` or [add new company - KEA]
> add new company - KEA

- README.md
- company-profiles/spotify.md
> Add new company - Spotify

- company-profiles/red-hat.md
📝Title your pull request descriptively. `[edit Red Hat]`
If updating or adding a company, please include details here: Added additional corporate, product, and hiring details
> [edit Red Hat]

- README.md
- company-profiles/ffw-agency.md
- company-profiles/ffwagency.md
> Add new company - FFW Agency

- README.md
- company-profiles/calibre.md
> Add new company - Calibre

- README.md
- company-profiles/mercari.md
> Add new company - Mercari

- README.md
Greetings dear fellows,
This PR fixes our companys domain name mentioned in README.md
You can check validity by following the new link. :)
Best,
Rust
> voiio: correct company domain

- README.md
- company-profiles/carecru.md
> Add new company - CareCru Inc.

- README.md
- company-profiles/bit-zesty.md
> add new company - Bit Zesty

- README.md
- company-profiles/airbyte.md
> Add new company - Airbyte

- README.md
- company-profiles/wemakemvp.md
> add new company - WeMakeMVP

- README.md
- company-profiles/eco-mind.md
> add new company - Eco-Mind

- README.md
- company-profiles/prezi.md
> Add new company - Prezi

- README.md
- company-profiles/acivilate.md
If updating or adding a company, please include details here: Adding Acivilate as a new company
> Add new company - Acivilate

- README.md
- company-profiles/aivitex.md
> Edit AIVITEX

- README.md
> Edit Link11

- company-profiles/zeit-io.md
> Edit Zeit.io

- README.md
- company-profiles/airbank.md
Adding [Airbank](https://www.joinairbank.com/), German fintech, fully remote setup allowed, currently with open tech positions.
> Add new company - Airbank

- PULL_REQUEST_TEMPLATE.MD
- README.md
- company-profiles/testgorilla.md
> add new company - TestGorilla

- company-profiles/implisense.md
This pull request fixes a typo.
> Edit Implisense

- company-profiles/sutherland-cloudsource.md
This pull request fixes a typo.
> Edit Sutherland CloudSource

- company-profiles/zignaly.md
This pull request fixes a typo.
> Edit Zignaly

- company-profiles/data-science-brigade.md
This pull request fixes a broken link.
> Edit Data Science Brigade

- company-profiles/knack.md
This pull request updates the link to avoid a redirect.
> Edit Knack

- README.md
- company-profiles/superplayer-and-co.md
This pull request fixes the domain name and application link.
> Edit Superplayer & Co

- README.md
- company-profiles/betterup.md
This pull request fixes the domain name and company links.
> Edit BetterUp

- README.md
This pull request fixes the domain name.
> Edit SignEasy

- README.md
This pull request fixes the domain name.
> Edit Sysdig

- README.md
- company-profiles/spoqa.md
This pull request fixes the domain name and application link.
> Edit Spoqa

- README.md
This pull request fixes the company link.
> Edit Transition Technologies

- README.md
This pull request fixes the company link.
> Edit Teamflow

- company-profiles/cyber-whale.md
This pull request fixes a broken link.
> Edit Cyber Whale

- README.md
This pull request cleans up various spaces in the table, and also removes superfluous Emoji Unicode characters. This can be checked recursively with:
`grep -r '\x{FE0F}' .`
> Improve and fix whitespace in README

- company-profiles/dalenys.md
This pull request updates the application link.
> Edit Dalenys

- README.md
- company-profiles/oreilly-online-learning.md
This pull request updates the link to avoid a redirect.
> Edit Safari Books Online

- README.md
- company-profiles/zenrows.md
> add new company - ZenRows

- README.md
- company-profiles/zamp.md
> Add new company - ZAMP

- README.md
- company-profiles/sommo.md
> add new company - Sommo

- README.md
- company-profiles/onna.md
If updating or adding a company, please include details here: Adding Onna to list of remote companies
> add new company -  Onna

- README.md
- company-profiles/broadwing.md
> add new company - Broadwing

- .github/FUNDING.yml
I’m approved for GH Sponsors on my personal profile so fixing that here.
Signed-off-by: Doug Aitken <dougaitken@users.noreply.github.com>
> Uncomment username from FUNDING.yml

- README.md
- company-profiles/mycelium.md
If updating or adding a company, please include details here: Updated the README and the .md file for Mycelium. 
Added all the information I could find, updated with the correct URL, and added the correct regions to the README when I removed the alert symbol.
> Editing "Mycelium" company information 

- README.md
- company-profiles/revolut.md
> Add new company - Revolut

- README.md
- company-profiles/civo.md
> Add new company - Civo

- README.md
- company-profiles/mixrank.md
> add new company - MixRank

- README.md
- company-profiles/two.md
> Add Two.ai company profile

- README.md
- company-profiles/flip.md
*I would add this company, as they're going towards the future of work, work from anywhere culture. It means their employees can choose how and from where they want to work, they can opt to work from the office or work remotely permanently. [Read more](https://tech.flip.id/how-flip-is-adopting-the-future-of-work/)*
> Add a new company - Flip

- company-profiles/oddball.md
- company-profiles/olist.md
- company-profiles/outsourcingdev.md
- company-profiles/pagepro.md
- company-profiles/payu.md
- company-profiles/precision-nutrition.md
- company-profiles/recurly.md
- company-profiles/redox.md
- company-profiles/remote-garage.md
- company-profiles/simpletexting.md
- company-profiles/sommo.md
- company-profiles/spreaker.md
- company-profiles/superplayer-and-co.md
- company-profiles/surevine.md
- company-profiles/tatvasoft.md
- company-profiles/tenable.md
- company-profiles/test-double.md
- company-profiles/toptal.md
- company-profiles/tractionboard.md
- company-profiles/transition-technologies-advanced-solutions.md
- company-profiles/upwork-pro.md
- company-profiles/veryfi.md
- company-profiles/webdevstudios.md
- company-profiles/zip-co.md
----
This fixes typos within company profiles. After this is merged I will help with #485.
> fix: Typos

- README.md
- company-profiles/questdb.md
> Add QuestDB

- company-profiles/bright-funds.md
- company-profiles/britecore.md
- company-profiles/featurist.md
> fix: Added Some Missing Info

- README.md
- company-profiles/devsquad.md
- [x ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
> Add new company - Devsquad

- README.md
- company-profiles/eatstreet.md
If updating or adding a company, please include details here: EatStreet is a food delivery company based in the Midwestern US that strives to be one of the best food delivery experiences. 
- [X ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters
> Add New Company - EatStreet

- company-profiles/harvest.md
I'm a current employee at Harvest. The previous information was outdated with broken links, so I updated it. 
> edit Harvest company

- README.md
- company-profiles/lightspeed.md
> Add new company - LIGHTSPEED POS

- company-profiles/hypergiant.md
Signed-off-by: Craig J. Midwinter <craig.j.midwinter@gmail.com>
If updating or adding a company, please include details here: Update link to careers page
> [Edit Hypergiant] Update careers link

- README.md
- company-profiles/digitise.md
If updating or adding a company, please include details here: I have added a new company called Digitise. It is hires remotely and most of the adverts are on LinkedIn. The company does not have its own website.
> [Add new company -Digitise]

- README.md
- company-profiles/gft.md
> Add new company - GFT

- README.md
- company-profiles/dashlane.md
> add new company - Dashlane

- README.md
- company-profiles/sticker-mule.md
> add new company sticker-mule 

- README.md
- company-profiles/turing.md
> Added turing.com

- README.md
- company-profiles/efishery.md
_Founded in 2013, eFishery is the first Aquaculture Technology startup in Asia that develops innovations in the aquaculture field. eFishery disrupts traditional fish farming methods and provides cutting edge solutions in the aquaculture ecosystem by offering an end-to-end platform that provides access to feed, financing, and market to fish and shrimp farmers._
This Pull Request should adhere to the repository's [Code of …
> add new company - eFishery

- README.md
- company-profiles/shippabo.md
> [add new company - Shippabo]

- README.md
- company-profiles/netapp.md
> Adding new company - NetApp

- README.md
- company-profiles/donut.md
> add new company - DONUT APP

- README.md
- company-profiles/cuvette.md
- [. ] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [. ] The company directly hires employees. No bootcamps / freelance sites / etc
- [. ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [ .] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [. ] __Remote status__ has details regarding how the culture includes remote …
> Added new Company - Cuvette

- README.md
- company-profiles/jobsity.md
> Add New Company - Jobsity Nearshore

- README.md
- company-profiles/powerschool.md
If updating or adding a company, please include details here: Edit PowerSchool technologies and locations
> Edit PowerSchool Information

- README.md
- company-profiles/meteorops.md
> Add meteorops

- README.md
- company-profiles/sendwave.md
> [Add new company - Sendwave]

- README.md
- company-profiles/clickup.md
> [Add new company-ClickUp]

- .github/CODE_OF_CONDUCT.md
- .github/PULL_REQUEST_TEMPLATE.MD
> Housekeeping - update CoC version and PR template

- README.md
updated remote location work of Wells fargo & Sysdig
Signed-off-by: Chinmay Kotkar <102941004+Chinmay-03@users.noreply.github.com>
> updated remote work location of Wells fargo & Sysdig 

- README.md
- company-profiles/atlassian.md
> Added Atlassian

- README.md
- company-profiles/granicus.md
Title your pull request descriptively. [edit X company] or [add new company - COMPANY]
If updating or adding a company, please include details here: delete this and add details
> Add new company - Granicus

- README.md
- company-profiles/code-like-a-girl.md
Added Code Like a Girl company profile and listing. Code Like a Girl are a remote tech company based in Australia. 
If accepted, can you please add #hacktoberfest-accepted tag to the PR? <3
> Add new company - CODE LIKE A GIRL

- README.md
- company-profiles/cancom.md
> Adding new company - CANCOM

- README.md
- company-profiles/dropbox.md
> feat: Added New Company - Dropbox

- README.md
- company-profiles/inshorts.md
This is a modified version of the [Contributing …
> Added inshorts.md as a remote company

- README.md
- company-profiles/meridianlink.md
- [] You know your alphabet - company is listed in alphabetical order in the README.md …
> Adding New Company - MeridianLink

- README.md
- company-profiles/clootrack.md
> [Add new company-Clootrack]

- README.md
- company-profiles/applaudo.md
> Add new company - Applaudo

- README.md
- company-profiles/edgio.md
> Add new company - Edgio

- README.md
- company-profiles/nvidia.md
- [] You know your alphabet - company is listed in alphabetical order in the README.md …
> Added Nvidia Company 

- README.md
- company-profiles/alami.md
This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/main/.github/CODE_OF_CONDUCT.md).
_ALAMI is the world's first sharia challenger bank based in Indonesia, starting out in 2019 as a sharia-compliant peer-to-peer lending platform for SME financing. Today, we have disbursed more than US$200 million for over 8,500 SMEs financing transactions with 0% default rate. ALAMI has also been awarded as the World's Best Islamic P2P Lending Platform in 2020 by The Asset Triple A and World Islamic Finance Award (WIFA). In …
> add new company - Alami

- company-profiles/factorialhr.md
Signed-off-by: Oriol Gual <oriolgual@users.noreply.github.com>
If updating or adding a company, please include details here: Updated people count and career link.
> Edit FactorialHR

- README.md
- company-profiles/ocient.md
If updating or adding a company, please include details here: Added company Ocient. 
- []x The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
This is a modified version of the [Contributing …
> add new company - Ocient

- README.md
- company-profiles/aerostrat.md
> Add New Company - Aerostrat

- README.md
- company-profiles/fiverr.md
- [] You know your alphabet - company is listed in alphabetical order in the README.md …
> Add new company - Fiverr

- README.md
- company-profiles/primer.md
If updating or adding a company, please include details here: Add Primer company
> add new company - Primer

- README.md
- company-profiles/godaddy.md
> added GoDaddy company 

- README.md
- company-profiles/bounteous.md
> Added new company - Bounteous

- README.md
- company-profiles/data-science-dojo.md
> Add new company - Data Science Dojo

- README.md
- company-profiles/teravision-technologies.md
Title your pull request descriptively. `[Add new company - Teravision Technologies]` 
> Add new company - Teravision Technologies

- README.md
- company-profiles/adeva.md
_Adeva is a global talent network that enables work without boundaries by connecting organizations with distributed tech talent across the world_
.
> add new company - ADEVA

- README.md
- company-profiles/beyond-company.md
- company-profiles/beyondcompany.md
> Add new company - Beyond Company

- README.md
- company-profiles/ordermentum.md
Title your pull request descriptively. `Ordermentum company`
If updating or adding a company, please include details here: Adding company Ordermentum
> Adding Ordermentum

- README.md
- company-profiles/cwt.md
> add new company - CWT

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.MD
- README.md
> Copy edits and region tweaks.

- README.md
- company-profiles/mindful.md
Updated README.md to include Mindful
Created a company-profile for Mindful (mindful.md)
> add new company - Mindful

- README.md
- company-profiles/virta-health.md
> add new company - Virta Health

- README.md
- company-profiles/smmile-digital.md
> add new company - Smmile Digital

- README.md
- company-profiles/bluecat-networks.md
> add new company - BlueCat Networks

- README.md
- company-profiles/zolar.md
> add zolar company

- README.md
- company-profiles/chess.md
> [ADD] New job entry (Chess.com)

- README.md
- company-profiles/brainstorm-force.md
> add new company -  Brainstorm Force

- README.md
---
Some standardisation of regions in the readme
> fix: Standardisation to README regions.

- README.md
- company-profiles/replit.md
> Add new company - Replit

- README.md
- company-profiles/safeguard-global.md
---
Closes #1341 
/cc @garethjmsaunders
> feat: Add Safeguard-Global

- README.md
- company-profiles/mayvue.md
* [X ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [X ] The company directly hires employees. - BOTH ** No bootcamps / freelance sites / etc**
* [ X] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [ X] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [ X] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [ X] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [X ] __Region__ details …
> Add new company - Mayvue Solutions

- README.md
- company-profiles/coalition-technologies.md
Signed-off-by: Khushi Shukla <tusharika.shukla05@gmail.com>
> add new company - Coalition technologies

- README.md
- company-profiles/automattic.md
> Update Automattic company profile for end of 2022

- README.md
- company-profiles/brikl.md
> Add new company - Brikl

- README.md
- company-profiles/packlink.md
Readd of #1180 as part of #1206 
-----
> feat: Add Packlink

- README.md
- company-profiles/intuit.md
* [ X ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ X ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [ X ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [ X ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [ X ] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [ X ] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [ X ] __Remote status__ has …
> Intuit Inc.

- README.md
- company-profiles/massive-pixel-creation.md
Readd of #1179 as part of #1206 
----
> feat: Add Massive Pixel Creation

- README.md
- company-profiles/gerencianet.md
> Added Gerencianet - Brazil

- README.md
- company-profiles/hashex.md
> HashEx company

- README.md
- company-profiles/alan.md
> Add Alan company

- README.md
> edit alan website url

- README.md
- company-profiles/lifen.md
> Add new Company - Lifen

- README.md
- company-profiles/wolverine-trading.md
> Feat: Add new remote company - Wolverine Trading

- README.md
- company-profiles/webrunners.md
> add new company - Webrunners

- company-profiles/aula.md
Signed-off-by: Devender <49671176+raoshaab@users.noreply.github.com>
> Added new Career Page in Aula.md

- company-profiles/argyle.md
Signed-off-by: Devender <49671176+raoshaab@users.noreply.github.com>
> Updated Carrer Page in Argyle

- company-profiles/britecore.md
Signed-off-by: Devender <49671176+raoshaab@users.noreply.github.com>
> Updated bitrecore Career Page Link

- README.md
- company-profiles/revolgy.md
> Add new company - Revolgy

- README.md
- company-profiles/railscarma.md
> Adding railscarma

- README.md
- company-profiles/epsy-health.md
- company-profiles/epsy.md
> add new company - Epsy Health

- company-profiles/abiturma.md
Update company's address and legal status
Signed-off-by: abiturma <aaron.kunert@abiturma.de>
* [x ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [x ] You are an employee of the company mentioned and confirm all included details are correct.
> edit abiturma company

- README.md
- company-profiles/zemoso.md
> Add new company - Zemoso

- README.md
- company-profiles/primotly.md
> Add new company - Primotly

- README.md
- company-profiles/mayven-studios.md
> Add new company - Mayven Studios

- README.md
- company-profiles/doit.md
> add new company - Doit

- README.md
- company-profiles/svix.md
> add new company - Svix

- README.md
- company-profiles/intent.md
> Add new company - Intent

- README.md
- company-profiles/coforma.md
> add new company - Coforma

- README.md
- company-profiles/netris.md
> edit Netris company

- README.md
- company-profiles/encora.md
> Adding company Encora

- README.md
- company-profiles/headforwards.md
> added new company - Headforwards

- README.md
- company-profiles/positiwise.md
> Add: Company Profile - Positiwise

- README.md
- company-profiles/shattered-silicon.md
> Added Shattered Silicon database consultancy company.

- README.md
- company-profiles/yahoo.md
> Add new company - Yahoo!

- README.md
- company-profiles/aha.md
> Edit Aha.io Company

- site/templates/404.html
The title was old copied for Colorlib, now it's updated as the page could not be found.
> UPDATE: 404.html

- README.md
- company-profiles/swiggy.md
> add new company - Swiggy

- README.md
- company-profiles/3blocks.md
> add new company - 3Blocks

- README.md
- company-profiles/seatgeek.md
> Added a new company (SeatGeek)

- README.md
- company-profiles/deel.md
> add new company - Deel

- README.md
- company-profiles/atento.md
> added company - Atento

- README.md
- company-profiles/cosmic-chimps.md
> Added new Company - Cosmic Chimps

- README.md
- company-profiles/capgemini.md
> add new company- Capgemini

- README.md
- company-profiles/exoscale.md
> added Exoscale

- README.md
- company-profiles/remotemore.md
> add company - RemoteMore

- .github/CONTRIBUTING.md
- README.md
- company-profiles/inter-link.md
> Add Inter.link company profile

- README.md
- company-profiles/namecheap.md
> Add new company - Namecheap

- README.md
- company-profiles/90-seconds.md
> add new company - 90 Seconds

- README.md
- company-profiles/invesco.md
> add new company - Invesco

- README.md
- company-profiles/capmo.md
> add new company - Capmo

- README.md
- company-profiles/sonatype.md
> add new company - Sonatype

- README.md
- company-profiles/joor.md
> Add new company - JOOR

- README.md
- company-profiles/logrocket.md
> add new company - LOGROCKET

- README.md
- company-profiles/hubspot.md
> Added Hubspot to company list

- README.md
- company-profiles/fdte.md
> add new company - FDTE

- README.md
- company-profiles/transfeera.md
> feat: add transfeera company

- README.md
- company-profiles/compucorp.md
> updated compucorp outdated links

- README.md
- company-profiles/roadpass-digital.md
> Added new remote company: Roadpass-Digital

- README.md
- company-profiles/extreme-networks.md
> Added new company Extreme Networks

- README.md
- company-profiles/ebury.md
> Added new company Ebury

- README.md
- company-profiles/picpay.md
> add new company - Picpay

- README.md
- company-profiles/cratedb.md
> add new company CRATEDB

- README.md
- company-profiles/folotop.md
> Folotop - we are new group who doing review the top 10 thing

- README.md
- company-profiles/firehire.md
Add FireHire company profile and update readme.
> Add new company - FireHire

- README.md
- company-profiles/cloudlinux.md
- company-profiles/dave.md
* [y ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [y ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [y ] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [ y] An entry has been added or edited within the [readme.md file](../../main/README.md).
> added Dave company (updated)

- company-profiles/marsbased.md
Updated as of 03/01/2024
* [ x] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [x ] You are an employee of the company mentioned and confirm all included details are correct.
* [x ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x ] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [ x] __Remote …
> Edit MARSBASED company

- README.md
- company-profiles/kestra.md
> add company Kestra

- README.md
- company-profiles/sardine-ai.md
> add sardine.ai

- README.md
- company-profiles/gmbapi.md
Adding new company GMBapi.com
- added to the list in  README
- added file in company-profiles with proper structure including vacancy url
DO NOT DELETE ANYTHING IN THIS COMMENT.
-->
> add company GMBapi

- company-profiles/ad-hoc.md
Quick update to reflect the current size of the company.
> Edit Ad Hoc company

- README.md
- company-profiles/tide.md
> add new company - Tide

- README.md
- company-profiles/asana.md
> add new company - Asana

- README.md
- company-profiles/wyeworks.md
> Add new company - WYEWORKS

- README.md
- company-profiles/veeva.md
> Add Veeva Systems remote company

- README.md
- company-profiles/klanik.md
> Add Klanik

- README.md
- company-profiles/dropbox.md
Edit Dropbox company: updating regions.
See issue #1808.
> Edit Dropbox company (issue #1808) (Hacktoberfest 2024)

- README.md
- company-profiles/datadog.md
Edit Datadog company: updating regions.
See issue #1808.
> Edit Datadog company (issue #1808) (Hacktoberfest 2024)

- README.md
- company-profiles/searchapi.md
> add new company - SearchApi

- README.md
- company-profiles/the-home-depot.md
> add new company - THD

- README.md
- company-profiles/zaneffi.md
> add new company - Zaneffi

- README.md
- company-profiles/crazygames.md
> Added crazygames company

- README.md
- company-profiles/code-b-solutions.md
> add new company - Code B Solutions

- README.md
- company-profiles/aiir.md
> add new company - Aiir

- README.md
- company-profiles/wirefuture.md
> Add new company - WireFuture

- company-profiles/tide.md
> Edit Tide company

- company-profiles/airtreks.md
> [Bug] Fixes: #1801 AirTreks "How to apply" link does not work correctly

- README.md
- company-profiles/paypay.md
> Added the Paypay Corporation for Hacktoberfest 2024.

- README.md
- company-profiles/akamai.md
> Added Akamai Technologies in Remote-Jobs Hacktoberfest 2024

- README.md
- company-profiles/atozdebug.md
> add new company - AtoZDebug

- README.md
- company-profiles/appen.md
> Added Appen company

- README.md
- company-profiles/quicktrials.md
> Add new company - QuickTrials

- README.md
- company-profiles/webscrapinghq.md
> Adding WebScrapingHQ to company profiles

- README.md
- company-profiles/flowpath.md
> Adding new company FlowPath

- README.md
- company-profiles/fyle.md
> add new company - Fyle

- README.md
Note : 
As per [Astronomer's](https://www.astronomer.io/careers/) career website's open positions, the firm has now opened positions in India as well which are remote in nature.
* [] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters
> fix: Astronomer hiring locations

- README.md
- company-profiles/ecosmic.md
> Add new company - Ecosmic

- README.md
- company-profiles/nearform.md
> [new company] - Nearform

- README.md
- company-profiles/codingcops.md
> Create CodingCops Company Profile and Update Readme file

- README.md
- company-profiles/scaloy.md
> add new company - SCALOY

- company-profiles/serpapi.md
**Changes:**
* Displaying a more comprehensive list of APIs we support
* Updated company size to [reflect current range](https://serpapi.com/team)
* Included Slack in the communication description
* Included additional technologies used at the company
* Updated to include the HQ location
* Changed the link for open roles to the careers page instead of the teams page
**Checklist:**
> Edit SerpApi company

- README.md
- company-profiles/a-1-auto-transport.md
* Create a-1-auto-transport.md
* Update README.md
> Add A-1 Auto Transport

- README.md
- company-profiles/rendr-software-group.md
> [New Company] Rendr Software Group

- site/assets/companies-table.js
- site/assets/site.css
This PR enhances the existing search functionality on the companies table by expanding search capabilities beyond just company names.
- Extended search logic to include company technologies and regions
- Updated search algorithm to check `companyTechnologies` and `region` fields
- Maintained backward compatibility with existing search behavior
- Added null checks to prevent errors when fields are missing
- Added `min-width: 200px` to `#search-input` for improved visual consistency
- Ensures search input maintains readable width across different screen sizes
**Before:**
```javascript
var companyName = company.nameText.toLowerCase();
if(companyName.includes(searchValue)){ …
```
> Search functionality updated for technology and region

- README.md
- company-profiles/three-movers.md
Create three-movers.md
Update README.md
> Add Moving Company

- README.md
- company-profiles/upcell.md
* [X ] You are an employee of the company mentioned and confirm all included details are correct.
* [X ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [X ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [X ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [X ] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [X ] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [X ] __Remote status__ has details regarding how the culture includes …
> Add new company - upcell

- README.md
- company-profiles/treez.md
> Add new company - Treez

- README.md
- company-profiles/capital-placement.md
> Adding Capital Placement Company

- README.md
- company-profiles/indrive.md
> added inDrive company

- .github/CONTRIBUTING.md
- README.md
- company-profiles/argyle.md
- company-profiles/convert.md
- company-profiles/foh-and-boh.md
Removed links from titles for these 3 companies (and updated names to way they use it on their sites), as they are the only ones who had links:
- [Argyle](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/argyle.md),
- [Convert](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/convert.md),
- [Foh&Boh](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/fohandboh.md),
or we should add links to all other companies.
Also updated Contributing Guidelines — removed this requirement.
> Edit Argyle, Convert, Foh&Boh companies: remove link from company name in profile, update names

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.MD
- .github/scripts/generate_report_script.js
- .github/scripts/package.json
- .github/scripts/validate_profiles_script.js
- .github/scripts/validate_readme_script.js
- .github/workflows/pr-validation.yml
because I vibe coded the shit out of this. 
This PR introduces a comprehensive automated validation system for the remote-jobs repository that will significantly improve the quality and consistency of contributions.
- ✅ **README.md validation**: Checks alphabetical ordering, duplicate companies, URL validity
- ✅ **Company profile validation**: Ensures all required sections are present and complete
- ✅ **Content quality checks**: Detects placeholder text, broken links, insufficient content
- ✅ **Cross-validation**: Verifies README entries match their company profiles
- ✅ **Intelligent reporting**: Provides detailed, actionable feedback via PR comments
- 🤖 **Automated PR comments** with comprehensive validation reports
- 🏷️ **Smart labeling system** (`validation-passed`, …
> Add Automated PR Validation System

- README.md
- company-profiles/zitadel.md
> add new company - Zitadel

- README.md
- company-profiles/rechat.md
> fixes 1768

- README.md
- company-profiles/turtlemint.md
> Add Turtlemint to company profiles and update README

- README.md
- company-profiles/employment-hero.md
This is a modified version of, and should adhere to, the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/main/.github/CONTRIBUTING.md).
---
**Note:** Our automated validation system will check your submission and provide feedback. Please address any issues found before requesting review.
> Add Employment Hero to company profiles
